uploads = []
outputs = []

[[generated]]
id = "of4Gr_F3Ax_xHKlaFcJKH"
uri = "file://artifacts/forester-dash/src/assets/forester-topdown.png"
type = "image"
title = "forester topdown blue"

[[generated]]
id = "QqozzmulZZZjdZ90lyzIg"
uri = "file://artifacts/forester-dash/src/assets/forester-hero.png"
type = "image"
title = "forester hero dark"
